// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy2de1EKrRDNSEWrB8GXWhE5QI0BtqL2I',
    appId: '1:110807358699:web:33587b32850faf2b8db2ae',
    messagingSenderId: '110807358699',
    projectId: 'reddit-clone-381af',
    authDomain: 'reddit-clone-381af.firebaseapp.com',
    storageBucket: 'reddit-clone-381af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMYja2s5ODGNWU7K_6UJySgYEzGsi4XBI',
    appId: '1:110807358699:android:47871cd0183588158db2ae',
    messagingSenderId: '110807358699',
    projectId: 'reddit-clone-381af',
    storageBucket: 'reddit-clone-381af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-fjXaytxmDavIwfzVZYlpgxQGw0Po7qA',
    appId: '1:110807358699:ios:ce882484a6c1abd28db2ae',
    messagingSenderId: '110807358699',
    projectId: 'reddit-clone-381af',
    storageBucket: 'reddit-clone-381af.appspot.com',
    androidClientId: '110807358699-373p14r2sin8h6vhacum5mtp9cq0va8v.apps.googleusercontent.com',
    iosClientId: '110807358699-q2qp7crectmjvkcjrhlj49vsqvv1nri9.apps.googleusercontent.com',
    iosBundleId: 'com.example.reeeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-fjXaytxmDavIwfzVZYlpgxQGw0Po7qA',
    appId: '1:110807358699:ios:ce882484a6c1abd28db2ae',
    messagingSenderId: '110807358699',
    projectId: 'reddit-clone-381af',
    storageBucket: 'reddit-clone-381af.appspot.com',
    androidClientId: '110807358699-373p14r2sin8h6vhacum5mtp9cq0va8v.apps.googleusercontent.com',
    iosClientId: '110807358699-q2qp7crectmjvkcjrhlj49vsqvv1nri9.apps.googleusercontent.com',
    iosBundleId: 'com.example.reeeeApp',
  );
}
